/*
 * PodTube - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using PodTube.Attributes;

using Microsoft.AspNetCore.Authorization;
using PodTube.BLL.Services;
using PodTube.Shared.Models.DTO;

namespace PodTube.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    [Route("api/channel")]
    public class ChannelApiController : ControllerBase {
        private ChannelService ChannelService { get; set; }
        public ChannelApiController(ChannelService channelService) : base() {
            this.ChannelService = channelService;
        }
        /*/// <summary>
        /// Deletes a channel and all of it&#x27;s videos
        /// </summary>
        /// <param name="channelId">ID of channel to delete</param>
        /// <response code="200">Successful operation</response>
        /// <response code="404">Video not found</response>
        /// <response code="405">Validation exception</response>
        [HttpDelete]
        [Route("/channel/{channelId}")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "ChannelChannelIdDelete")]
        public virtual IActionResult ChannelChannelIdDelete([FromRoute][Required]long? channelId)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);

            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            //TODO: Uncomment the next line to return response 405 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(405);

            throw new NotImplementedException();
        }*/

        /// <summary>
        /// Get metadata of a channel
        /// </summary>
        /// <param name="channelId">ID of channel to return</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid ID supplied</response>
        /// <response code="404">Channel not found</response>
        /// <response code="405">Validation exception</response>
        [HttpGet("{channelId}")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "GetChannelById")]
        [SwaggerResponse(statusCode: 200, type: typeof(ChannelDto), description: "Successful operation")]
        public virtual IActionResult GetChannelById([FromRoute][Required] long channelId) {
            var result = ChannelService.GetChannelById(channelId);

            if (result == null) {
                return StatusCode(404);
            }

            return new ObjectResult(result.ToJson());
        }

        /// <summary>
        /// Get videos uploaded to a channel
        /// </summary>
        /// <param name="channelId">ID of channel to return</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid ID supplied</response>
        /// <response code="404">Channel not found</response>
        /// <response code="405">Validation exception</response>
        [HttpGet("{channelId}/videos")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "GetChannelVideos")]
        [SwaggerResponse(statusCode: 200, type: typeof(VideoPagedListDto), description: "Successful operation")]
        public virtual IActionResult GetChannelVideos([FromRoute][Required] long channelId, [FromQuery][Required] int page, [FromQuery][Required] int limit) {
            var result = ChannelService.GetPagedVideosByChannelId(channelId, page, limit);

            if (result == null) {
                return StatusCode(404);
            }

            return new ObjectResult(result.ToJson());
        }

        /// <summary>
        /// Get a paged list of all channels
        /// </summary>
        /// <param name="page">Number of the currentpage</param>
        /// <param name="limit">Number of channels on a page</param>
        /// <response code="200">Successful operation</response>
        /// <response code="405">Validation exception</response>
        [HttpGet]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "GetChannelsPaged")]
        [SwaggerResponse(statusCode: 200, type: typeof(ChannelPagedListDto), description: "Successful operation")]
        public virtual IActionResult GetChannelsPaged([FromQuery][Required()] int page, [FromQuery][Required()] int limit) {
            var result = ChannelService.GetChannelsPaged(page, limit);

            if (result == null) {
                return StatusCode(404);
            }

            return new ObjectResult(result.ToJson());
        }

        ///// <summary>
        ///// Create a new channel
        ///// </summary>
        ///// <param name="body"></param>
        ///// <response code="200">Successful operation</response>
        ///// <response code="405">Invalid input</response>
        //[HttpPost]
        //[Route("/channel")]
        //[ValidateModelState]
        //[SwaggerOperation(OperationId = "ChannelPost")]
        //[SwaggerResponse(statusCode: 200, type: typeof(ChannelDto), description: "Successful operation")]
        //public virtual IActionResult ChannelPost([FromBody]ChannelRequestBody body)
        //{ 
        //    //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
        //    // return StatusCode(200, default(ChannelInfoWithOwner));

        //    //TODO: Uncomment the next line to return response 405 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
        //    // return StatusCode(405);
        //    string exampleJson = null;
        //    exampleJson = "\"\"";
            
        //                var example = exampleJson != null
        //                ? JsonConvert.DeserializeObject<ChannelInfoWithOwner>(exampleJson)
        //                : default(ChannelInfoWithOwner);            //TODO: Change the data returned
        //    return new ObjectResult(example);
        //}
    }
}
