/*
 * PodTube - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using PodTube.Attributes;

using Microsoft.AspNetCore.Authorization;
using PodTube.BLL.Services;
using PodTube.DataAccess.Entities;
using PodTube.Shared.Models.DTO;
using PodTube.Shared.Models.RequestBody;

namespace PodTube.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    [Route("api/playlist")]
    public class PlaylistApiController : ControllerBase
    { 
        private PlaylistService PlaylistService { get; set; }

        public PlaylistApiController(PlaylistService playlistService) {
            this.PlaylistService = playlistService;
        }

        /// <summary>
        /// Get a paged list of all playlists
        /// </summary>
        /// <param name="page">Number of the currentpage</param>
        /// <param name="limit">Number of playlists on a page</param>
        /// <response code="200">Successful operation</response>
        /// <response code="405">Validation exception</response>
        [HttpGet]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "GetPlaylistsPaged")]
        [SwaggerResponse(statusCode: 200, type: typeof(PlaylistPagedListDto), description: "Successful operation")]
        public virtual IActionResult GetPlaylistsPaged([FromQuery][Required()]int page, [FromQuery][Required()]int limit)
        {
            var result =  PlaylistService.GetAllPlaylists(page, limit);
            return new ObjectResult(result.ToJson());
        }

        /// <summary>
        /// Get metadata of a playlist
        /// </summary>
        /// <param name="playlistId">ID of playlist to return</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid ID supplied</response>
        /// <response code="404">Playlist not found</response>
        /// <response code="405">Validation exception</response>
        [HttpGet("{playlistId}")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "GetPlaylistById")]
        [SwaggerResponse(statusCode: 200, type: typeof(PlaylistDto), description: "Successful operation")]
        public virtual IActionResult GetPlaylistById([FromRoute][Required]long playlistId)
        {
            var result = PlaylistService.GetPlaylistById(playlistId);
            if(result == null) {
                StatusCode(404);
            }
            return new ObjectResult(result!.ToJson());
        }

        /// <summary>
        /// Get videos uploaded to a playlist
        /// </summary>
        /// <param name="playlistId">ID of playlist to return</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid ID supplied</response>
        /// <response code="404">Playlist not found</response>
        /// <response code="405">Validation exception</response>
        [HttpGet("{playlistId}/videos")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "GetPlaylistVideos")]
        [SwaggerResponse(statusCode: 200, type: typeof(VideoPagedListDto), description: "Successful operation")]
        public virtual IActionResult GetPlaylistVideos([FromRoute][Required]long playlistId, [FromQuery][Required] int page, [FromQuery][Required] int limit)
        {
            var result = PlaylistService.GetPagedVideosByPlaylistId(playlistId, page, limit);
            if (result == null) {
                StatusCode(404);
            }
            return new ObjectResult(result!.ToJson());
        }

        /// <summary>
        /// Create a new playlist
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="405">Invalid input</response>
        [HttpPost]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "PostCreatePlaylist")]
        [SwaggerResponse(statusCode: 200, type: typeof(PlaylistDto), description: "Successful operation")]
        public virtual IActionResult PostCreatePlaylist([FromBody]PlaylistRequestBody body)
        {
            var result = PlaylistService.CreateNewPlaylist(body);
            if(result == 0) {
                StatusCode(405);
            }
            return new ObjectResult(PlaylistService.GetPlaylistById(result));
        }

        /// <summary>
        /// Deletes a playlist and all of it&#x27;s videos
        /// </summary>
        /// <param name="playlistId">ID of playlist to delete</param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Unsuccessful operation</response>
        [HttpDelete("{playlistId}")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "DeletePlaylistById")]
        public virtual IActionResult DeletePlaylistById([FromRoute][Required] long playlistId) {
            var success = PlaylistService.DeletePlaylistById(playlistId);
            if (!success) {
                return StatusCode(400);
            }
            return StatusCode(200);
        }

        /// <summary>
        /// Add video to playlist
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid input</response>
        [HttpPost("{playlistId}/videos")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "PostAddVideoToPlaylistById")]
        [SwaggerResponse(statusCode: 200, type: typeof(PlaylistDto), description: "Successful operation")]
        public virtual IActionResult PostAddVideoToPlaylistById([FromRoute][Required] long playlistId, [FromQuery][Required] long videoId) {
            var success = PlaylistService.AddVideoToPlaylistByIds(playlistId, videoId);
            if (!success) {
                StatusCode(400);
            }
            return StatusCode(200);
        }

        /// <summary>
        /// Remove video from playlist
        /// </summary>
        /// <param name="body"></param>
        /// <response code="200">Successful operation</response>
        /// <response code="400">Invalid input</response>
        [HttpDelete("{playlistId}/videos")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "DeleteRemoveVideoFromPlaylistById")]
        [SwaggerResponse(statusCode: 200, type: typeof(PlaylistDto), description: "Successful operation")]
        public virtual IActionResult DeleteRemoveVideoFromPlaylistById([FromRoute][Required] long playlistId, [FromQuery][Required] long videoId) {
            var success = PlaylistService.RemoveVideoFromPlaylistByIds(playlistId, videoId);
            if (!success) {
                StatusCode(400);
            }
            return StatusCode(200);
        }
    }
}
