/*
 * PodTube - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using System.ComponentModel.DataAnnotations;
using PodTube.Attributes;

using Microsoft.AspNetCore.Authorization;
using PodTube.BLL.Services;
using PodTube.Shared.Models.DTO;
using PodTube.Shared.Models.RequestBody;
using System.Text.Json;

namespace PodTube.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    [Route("api/video")]
    public class VideoApiController : ControllerBase
    { 
        private VideoService VideoService { get; set; }
        public VideoApiController(VideoService videoService) : base() {
            this.VideoService = videoService;
        }

        [HttpGet]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "GetVideosDebug")]
        [SwaggerResponse(statusCode: 200, description: "Successful operation")]
        public virtual IActionResult GetVideosDebug() {
            var result = VideoService.GetAllVideos();
            return new ObjectResult(result);
        }

        ///// <summary>
        ///// Deletes a video
        ///// </summary>
        ///// <param name="videoId">ID of video to return</param>
        ///// <response code="200">Successful operation</response>
        ///// <response code="404">Video not found</response>
        ///// <response code="405">Validation exception</response>
        //[HttpDelete]
        //[Route("/video/{videoId}")]
        //[ValidateModelState]
        //[SwaggerOperation(OperationId = "VideoVideoIdDelete")]
        //public virtual IActionResult VideoVideoIdDelete([FromRoute][Required]long? videoId)
        //{ 
        //    //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
        //    // return StatusCode(200);

        //    //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
        //    // return StatusCode(404);

        //    //TODO: Uncomment the next line to return response 405 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
        //    // return StatusCode(405);

        //    throw new NotImplementedException();
        //}

        ///// <summary>
        ///// Get information and content of a video
        ///// </summary>
        ///// <param name="videoId">ID of video to return</param>
        ///// <response code="200">Successful operation</response>
        ///// <response code="400">Invalid ID supplied</response>
        ///// <response code="404">Video not found</response>
        ///// <response code="405">Validation exception</response>
        [HttpGet("{videoId}")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "GetVideoById")]
        [SwaggerResponse(statusCode: 200, type: typeof(VideoDto), description: "Successful operation")]
        public virtual IActionResult GetVideoById([FromRoute][Required]long videoId)
        {
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(FullVideoInfo));
            var result = VideoService.GetVideoById(videoId);

            if(result == null) {
                return StatusCode(404);
            }

            return new ObjectResult(result);
        }

        [HttpPost("upload")]
        [Consumes("multipart/form-data")]
        [ValidateModelState]
        [SwaggerOperation(OperationId = "PostUploadVideo")]
        [SwaggerResponse(statusCode: 200, type: typeof(VideoDto), description: "Successful operation")]
        public virtual IActionResult PostUploadVideo([FromForm][Required] string metadata, [FromForm][Required] List<IFormFile> files) {
            var metadataDto = JsonSerializer.Deserialize<VideoRequestBody>(metadata);
            var success = VideoService.UploadVideo(metadataDto!, files);
            if (!success) {
                return StatusCode(400);
            }
            return StatusCode(200);
        }
    }
}
