/*
 * PodTube - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace PodTube.Shared.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class FrameDto : IEquatable<FrameDto>
    { 
        [Required]
        [DataMember(Name="url")]
        public string Url { get; set; }

        [Required]
        [DataMember(Name="timestampStart")]
        public int TimestampStart { get; set; }

        [Required]

        [DataMember(Name = "timestampEnd")]
        public int TimestampEnd { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Frame {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  TimestampStart: ").Append(TimestampStart).Append("\n");
            sb.Append("  TimestampEnd: ").Append(TimestampEnd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FrameDto)obj);
        }

        /// <summary>
        /// Returns true if Frame instances are equal
        /// </summary>
        /// <param name="other">Instance of Frame to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FrameDto other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Url == other.Url ||
                    Url != null &&
                    Url.Equals(other.Url)
                ) && 
                (
                    TimestampStart == other.TimestampStart ||
                    TimestampStart != null &&
                    TimestampStart.Equals(other.TimestampStart)
                ) &&
                (
                    TimestampEnd == other.TimestampEnd ||
                    TimestampEnd != null &&
                    TimestampEnd.Equals(other.TimestampEnd)
                )
                ;
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Url != null)
                    hashCode = hashCode * 59 + Url.GetHashCode();
                    if (TimestampStart != null)
                    hashCode = hashCode * 59 + TimestampStart.GetHashCode();
                    if (TimestampEnd != null)
                    hashCode = hashCode * 59 + TimestampEnd.GetHashCode();
                return hashCode;
            }
        }

    }
}
