/*
 * PodTube - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace PodTube.Shared.Models.RequestBody {

    [DataContract]
    public class VideoRequestBody {
        /// <summary>
        /// Gets or Sets ParentChannel
        /// </summary>
        [Required]
        [JsonPropertyName("parentChannel")]
        public long ChannelId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>

        [JsonPropertyName("description")]
        public string Description { get; set; }

        [JsonPropertyName("frames")]
        public List<FrameRequestBody> Frames { get; set; }

        [JsonPropertyName("audio")]
        public string AudioFilename { get; set; }
    }
}
