/*
 * PodTube - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace PodTube.Shared.Models.RequestBody {

    [DataContract]
    public class VideoRequestBody 
    {
        /// <summary>
        /// Gets or Sets ParentChannel
        /// </summary>
        [Required]
        [DataMember(Name = "parentChannel")]
        public long ChannelId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [Required]
        [DataMember(Name = "name")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets or Sets Description
        /// </summary>

        [DataMember(Name = "description")]
        public string Description { get; set; } = string.Empty;

        [DataMember(Name = "frames")]
        public List<string> Frames { get; set; } = new();


        [DataMember(Name = "audio")]
        public string AudioFilename { get; set; } = string.Empty;

        public List<FrameRequestBody> GetFrames() {
            return Frames.Select(e => System.Text.Json.JsonSerializer.Deserialize<FrameRequestBody>(e)!).ToList() ?? new List<FrameRequestBody>();
        }
    }
}
