/*
 * PodTube - OpenAPI 3.0
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace PodTube.Shared.Models.DTO {
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class FrameDto {
        [Required]
        [DataMember(Name = "url")]
        [JsonPropertyName("url")]
        public string Url { get; set; }

        [Required]
        [DataMember(Name = "timestampStart")]
        [JsonPropertyName("timestampStart")]
        public int TimestampStart { get; set; }

        [Required]
        [DataMember(Name = "timestampEnd")]
        [JsonPropertyName("timestampEnd")]
        public int TimestampEnd { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString() {
            var sb = new StringBuilder();
            sb.Append("class Frame {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  TimestampStart: ").Append(TimestampStart).Append("\n");
            sb.Append("  TimestampEnd: ").Append(TimestampEnd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
    }
}
